URL: https://www.baidu.com     #这是yaml配置文件，目前配置了URL yaml格式的配置文件可以这样格式书写
log:
    file_name: test.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    parttern: '%(asctime)s-%(name)s-%(levelname)s-%(message)s'